$('body').terminal({
    ls: function(ls) {
        this.echo('fitness --info\n'+ 'mechs --info\n' +'pc --info');
    },
    fitness: function(fitness) {
        this.echo("Waarom ik dit graag doe\n\n - Doelen behalen\n - Tot het uiterste gaan\n - Grenzen verleggen\n - Hoofd leegmaken\n\n De hobby/interesse waar ik voornamelijk mee bezig ben is fitness. Een 2-tal jaar geleden ging ik met een vriend voor het eerst mee naar de fitness, zonder al te veel kennis of plannen.\n\n Intussen is dit uitgegroeid tot een ware passie. In het begin neigde ik meer naar de powerlifting kant van het verhaal, ondertussen gaan mijn interesses uit naar bodybuilding. \n\n Het leukste aan deze hobby vind ik het feit dat je constant je grenzen verlegt en constant opzoek bent naar meer. Het stellen van doelen en deze behalen is bijna verslavend. Ook geeft het je 2 uur per dag waarop je je hoofd volledig kan leegmaken. Het is voor mij tevens ook een echte stress relief.\n\n Het is natuurlijk niet enkel rozengeur en maneschijn. Het vergt enorm veel van je lichaam. Dit volhouden is niet altijd gemakkelijk.\n\n Ook is het soms moeilijk te combineren met school en andere hobby’s.\n\n Toch ben ik enorm blij dat ik deze wereld heb leren kennen. Ik voel me er goed in en ik zie mezelf dit nog zo lang mogelijk doen.\n\n");
    },
    mechs: function(mechs) {
        this.echo(" Waarom dit mij interesseert\n\n - Voorkeuren\n - Persoonlijkheid\n - Aesthetics\n - Kwaliteit\n\n Iets waar ik me sinds kort in interesseer zijn custom mechanical keyboards.\n\n We kennen allemaal wel de flashy, enorm luide mechanical ‘gamer’ keyboards. Ik denk dat dit een compleet verkeerd beeld schetst van wat toetsenborden kunnen zijn. \n\n Een toetsenbord is je voornaamste manier om met je computer te ‘communiceren’, waarom zou je dit dan niet zo aangenaam mogelijk willen maken? \n\n Het begon allemaal toen ik de vod’s van Taeha Types, één van de grootse figuren in deze hobby, op youtube begon te herbekijken.\n Volgens vele is de custom mech scene een typische ‘rabbit hole’, het is een hobby waar je in valt en moeilijk weer uit geraakt. Dit bleek helemaal waar te zijn. \n\n Het grootste pijnpunt in deze hobby zijn de absurde prijzen. Toetsenborden van rond de $800 zijn zeker niet absurd, zeker niet als het gaat om toetsenborden van bijvoorbeeld Keycult. \n\n Ook zijn de wachttijden vaak een afknapper voor mensen. De meeste producten zoals keyboard kits en keycap sets worden verkocht via ‘groupbuys’. \n\n Mensen in de community komen met een idee, plaatsten er een ‘IC’ (interest check) van op sites zoals  geekhack om te kijken of er genoeg interesse voor dit product is. <br /><br /> Als dit zo blijkt te zijn gaat het product in ‘groupbuy’, mensen kunnen dan het product een soort van ‘pre-orderen’. Met de opbrengst van de groupbuy wordt het project dan gefinancierd. \n\n Vaak zorgt dit ervoor dat producten 1 tot 2 jaar op zich kunnen laten wachten, na dat je er voor betaald hebt. \n\n Nu, waarom zou je dan een custom mech willen? Wel, je kan alles van top tot teen naar jou persoonlijke voorkeur aanpassen. Van kleuren tot geluid, typgevoel, layout, alles wat je je maar kan bedenken. \n\n Toch begint hier een positieve verandering in te komen, bedrijven zoals kbdfans en wuquestudio hebben keyboard kits die ready made zijn en in 'grote' oplagen worden gemaakt. Deze zijn dan vaak een stuk goedkoper en worden gemiddeld binnen de 1 tot 2 maanden geleverd. \n\n Toch zijn deze natuurlijk iets minder speciaal dan andere custom mech’s. Het is wel een uitstekende manier voor beginners om in de hobby te springen. \n\n Zelf heb ik een gok 7V kunnen bemachtigen via een extras raffle op mykeyboard.eu. Een prachtige mech vervaardigt uit aluminium, stainless steel weight, polycarb plate, gebouwd met lubed en filmed alpaca’s (krytox 205g0 en tx films).\n\n Deze build heeft mij uiteielijk een 700-tal Euro gekost. Gelukkig behouden, of stijgen, deze in waarde.");
    },
    pc: function(pc) {
        this.echo("Waarom dit mij interesseert\n\n - Prijs/kwaliteits verhouding\n - Aanpassen naar behoeften\n - Grote keuze\n\n De laatse hobby van mij zijn custom PC’s. Een aantal jaar geleden heb ik mijn eerste ‘gaming’ computergebouwd.\n\nOndertussen heb ik een aantal systemen voor vrienden en een voormalig stagementor van mij mogen bouwen\n\nIk kan met zekerheid zeggen dat mijn smaak hier in volledig is omgedraaid.\n\nEerst draaide alles erom dat het zo ‘flashy’ mogelijk was.\n\nOndertussen kies ik uitsluitend voor performance optimised components, met merken als Noctua bequiet!, founders editions gpu’s etc.\n\nWel, FE cards underperformen soms vanwege hun koeling en geen factory OC, maar dat terzijde, ze blijven wel het mooist.\n\nZelf heb ik niet zo lang geleden een 3070 Ti Founders Edition kunnen bemachtigen, een pracht van een kaart. \n\nOok heb ik kort met mini-ITX builds geëxperimenteerd, hier wil ik zeker nog in verder gaan maar dit blijkt een even grote ‘rabbit hole’ als custom mechs te zijn, eerst even sparen dus. Graag zou ik eens een build willen doen in de iqunix ZX-1 of thor zone mjolnir");
    }
}, {
    greetings: "Welkom! Type <ls ?> voor een lijst van beschikbare commando's"
});